name: Smart Backup CI
on:
  push:
   branches: [main]
jobs:
  backup-ci:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v5
     - name: Setup Python
       uses: actions/setup-python@v6
       with:
         python-version: 3.12  